### ISSUE TITLE
Figure out why echo doesn't support '-e' on travis

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/symbiflow-arch-defs#66]
On Travis we are getting `-e <string>` when we use `echo -e <string>`. On my local computer we just get `<string>` but echo is correctly interpreting the escape characters.

From the man page;
> `-e     enable interpretation of backslash escapes`

I'm guessing it has something to do with shell builtins verse real commands or something?

**Comment by mithro** [comment]
Example;
https://travis-ci.org/mithro/symbiflow-arch-defs/builds/350461107

![image](https://user-images.githubusercontent.com/21212/37111250-111fa6a6-21f4-11e8-8723-5b56b5841da8.png)

**Comment by elmsfu** [comment]
I think this is because make uses `sh` and the builtin `echo` doesn't support that option. https://stackoverflow.com/questions/589276/how-can-i-use-bash-syntax-in-makefile-targets

A few solutions:
1. You can just not use `-e` as by default sh respects the escape characters
1. set `SHELL = bash` to force using bash
1. define ECHO based on `SHELL` value and replace `echo -e` with `$(ECHO)`

Defining ECHO probably provides the most flexibility.

**Comment by mithro** [comment]
https://travis-ci.org/SymbiFlow/symbiflow-arch-defs/builds/351175350
